sudo: required

services:
  - docker

language: python

install:
  - python3 -m install molecule docker testinfra

script:
  - molecule test --scenario-name docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
