---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    capabilities:
      - ALL
    privileged: true
    pull: false
    groups:
      - docker
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
